### ISSUE TITLE
TODO: Use NPM instead of Grunt for uploading to screeps and other tasks.

### ISSUE THREAD

**Issue by chxcolate** [WalterDevelopment/screeps#1]
## Tasks:
- [x] ~Clean '**_dist_**' directory (which will be uploaded to Screeps)~
- [x] ~Copy files from the source directory to '**_dist_**' directory (with flattened file structure)~
- [x] ~_**Replace all imports with directory flattened imports.**_~
- [x] ~_Beautify Code_~
- [x] _Publish Code to Screeps using API_

@WilWa
